# Generated by Django 2.2.4 on 2019-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190829_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
