# Generated by Django 2.2.4 on 2019-08-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190828_1518'),
        ('login', '0002_auto_20190828_1117'),
    ]

    operations = [
    ]
