# Generated by Django 2.2.4 on 2019-08-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity_sign_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_act', models.CharField(blank=True, max_length=64, null=True)),
                ('uuid_user', models.CharField(blank=True, max_length=64, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
