# Generated by Django 2.2.4 on 2019-08-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_act', models.CharField(blank=True, max_length=64, null=True)),
                ('uuid_user', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
