# Generated by Django 2.2.4 on 2019-09-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yw', '0004_auto_20190901_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommended_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_act', models.CharField(blank=True, max_length=64, null=True)),
                ('stay_length', models.IntegerField(blank=True, max_length=720, null=True)),
            ],
        ),
    ]
