# Generated by Django 2.2.4 on 2019-08-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='On_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_act', models.UUIDField(blank=True, null=True)),
                ('uuid_user', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
