# Generated by Django 2.2.4 on 2019-08-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='on_site',
            name='uuid_act',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='on_site',
            name='uuid_user',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
