# Generated by Django 2.2.4 on 2019-09-07 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20190907_2252'),
        ('login', '0005_auto_20190907_2252'),
        ('personal_center', '0004_auto_20190829_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='on_site',
            name='uuid_act',
        ),
        migrations.RemoveField(
            model_name='on_site',
            name='uuid_user',
        ),
        migrations.AddField(
            model_name='on_site',
            name='activity',
            field=models.ForeignKey(db_column='uuid_act', max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
        migrations.AddField(
            model_name='on_site',
            name='user',
            field=models.ForeignKey(db_column='uuid_user', max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
