# Generated by Django 2.2.4 on 2019-08-30 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid1, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, default='其他', max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('start_time', models.CharField(blank=True, max_length=64, null=True)),
                ('end_time', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('organizer', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('logo', models.CharField(blank=True, max_length=256, null=True)),
                ('introduction', models.CharField(blank=True, default='这个人很懒，什么都没有留下。', max_length=256, null=True)),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('file_name', models.CharField(blank=True, max_length=128, null=True)),
                ('file_path', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
