# Generated by Django 2.2.4 on 2019-08-27 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('start_time', models.CharField(blank=True, max_length=64, null=True)),
                ('end_time', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('organizer', models.CharField(blank=True, max_length=128, null=True)),
                ('logo', models.CharField(blank=True, max_length=256, null=True)),
                ('introduction', models.CharField(blank=True, default='这个人很懒，什么都没有留下。', max_length=256, null=True)),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['-uuid'],
            },
        ),
    ]
