# Generated by Django 2.2.4 on 2019-08-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
        migrations.AddField(
            model_name='activity',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='status_process',
            field=models.CharField(blank=True, default='not_start', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='status_publish',
            field=models.CharField(blank=True, default='unpublished', max_length=64, null=True),
        ),
    ]
