# Generated by Django 2.2.4 on 2019-08-28 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('act_uuid', models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=128, null=True)),
                ('file_path', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
