# Generated by Django 2.2.4 on 2019-08-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_uploadrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrecord',
            name='act_uuid',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
