# Generated by Django 2.2.4 on 2019-09-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20190830_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('start_time', models.CharField(blank=True, max_length=64, null=True)),
                ('end_time', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('organizer', models.CharField(blank=True, max_length=128, null=True)),
                ('introduction', models.CharField(blank=True, max_length=256, null=True)),
                ('uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OldInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('start_time', models.CharField(blank=True, max_length=64, null=True)),
                ('end_time', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('organizer', models.CharField(blank=True, max_length=128, null=True)),
                ('introduction', models.CharField(blank=True, max_length=256, null=True)),
                ('uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
    ]
