# Generated by Django 2.2.4 on 2019-08-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20190828_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrecord',
            name='act_uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
