# Generated by Django 2.2.4 on 2019-09-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20190902_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('action', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NewInfo',
        ),
    ]
