# Generated by Django 2.2.4 on 2019-08-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20190828_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
