# Generated by Django 2.2.4 on 2019-09-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20190902_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='uuid',
            field=models.CharField(auto_created=True, default='<function uuid1 at 0x0354EC00>', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
