# Generated by Django 2.2.4 on 2019-09-07 22:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20190906_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminactivity',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='uploadrecord',
            name='act_uuid',
        ),
        migrations.AddField(
            model_name='adminactivity',
            name='activity',
            field=models.ForeignKey(db_column='uuid', max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='activity',
            field=models.ForeignKey(db_column='act_uuid', max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='uuid',
            field=models.CharField(auto_created=True, default=uuid.UUID('1cb2c1b8-d17f-11e9-b821-887873aca633'), editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
