# Generated by Django 2.2.4 on 2019-08-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20190829_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadRecord',
        ),
    ]
