# Generated by Django 2.2.4 on 2019-08-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_delete_uploadrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_uuid', models.CharField(max_length=64)),
                ('file_name', models.CharField(blank=True, max_length=128, null=True)),
                ('file_path', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
