# Generated by Django 2.2.4 on 2019-08-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_uploadrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrecord',
            name='act_uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
