# Generated by Django 2.2.4 on 2019-08-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20190829_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-c_time'], 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AddField(
            model_name='activity',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
