# Generated by Django 2.2.4 on 2019-08-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20190830_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-c_time',), 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
    ]
